//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NextTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\temp\TempCreds.xml.
        /// </summary>
        internal static string CredentialsPath {
            get {
                return ResourceManager.GetString("CredentialsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;cmd&quot;:&quot;depth&quot;,&quot;args&quot;:{&quot;i&quot;:&quot;2188&quot;,&quot;m&quot;:30,&quot;t&quot;:&quot;depth&quot;,&quot;tick_timestamp&quot;:&quot;2010-01-22 16:22:06&quot;,&quot;bid1&quot;:0.00,&quot;bid_volume1&quot;:0,&quot;ask1&quot;:120.00,&quot;ask_volume1&quot;:200,&quot;bid2&quot;:0.00,&quot;bid_volume2&quot;:0,&quot;ask2&quot;:0.00,&quot;ask_volume2&quot;:0,&quot;bid3&quot;:0.00,&quot;bid_volume3&quot;:0,&quot;ask3&quot;:0.00,&quot;ask_volume3&quot;:0,&quot;bid4&quot;:0.00,&quot;bid_volume4&quot;:0,&quot;ask4&quot;:0.00,&quot;ask_volume4&quot;:0,&quot;bid5&quot;:0.00,&quot;bid_volume5&quot;:0,&quot;ask5&quot;:0.00,&quot;ask_volume5&quot;:0}}.
        /// </summary>
        internal static string PublicFeedDepthMessage {
            get {
                return ResourceManager.GetString("PublicFeedDepthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;cmd&quot;:&quot;err&quot;, &quot;args&quot;:{&quot;msg&quot;:&quot;Not authorized.&quot;, &quot;cmd&quot;:{&quot;cmd&quot;:&quot;subscribe&quot;,&quot;args&quot;:{&quot;t&quot;:&quot;trading_status&quot;,&quot;i&quot;:&quot;998&quot;,&quot;m&quot;:&quot;11&quot;}}}}.
        /// </summary>
        internal static string PublicFeedErrorMessage {
            get {
                return ResourceManager.GetString("PublicFeedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;cmd&quot;:&quot;index&quot;,&quot;args&quot;:{&quot;i&quot;:&quot;SIX-IDX-DJI&quot;,&quot;m&quot;:&quot;SIX&quot;,&quot;t&quot;:&quot;index&quot;,&quot;tick_timestamp&quot;:&quot;2010-09-24 07:01:58&quot;,&quot;last&quot;:10662.4199,&quot;high&quot;:10761.9404,&quot;low&quot;:10640.9199,&quot;close&quot;:10739.31}}.
        /// </summary>
        internal static string PublicFeedIndexMessage {
            get {
                return ResourceManager.GetString("PublicFeedIndexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;cmd&quot;:&quot;price&quot;,&quot;args&quot;:{&quot;i&quot;:&quot;1843&quot;,&quot;m&quot;:30,&quot;t&quot;:&quot;price&quot;,&quot;trade_timestampBROKEN&quot;:&quot;2010-01-22 16:17:23&quot;,&quot;tick_timestamp&quot;:&quot;2010-01-22 16:18:42&quot;,&quot;bid&quot;:&quot;0.00&quot;,&quot;bid_volume&quot;:0,&quot;ask&quot;:101.00,&quot;ask_volume&quot;:200,&quot;close&quot;:101.00,&quot;high&quot;:101.00,&quot;last&quot;:101.00,&quot;last_volume&quot;:200,&quot;lot_size&quot;:&quot;1&quot;,&quot;low&quot;:101.00,&quot;open&quot;:0.00,&quot;turnover&quot;:6605400,&quot;turnover_volume&quot;:65400}}.
        /// </summary>
        internal static string PublicFeedMalformedMessage {
            get {
                return ResourceManager.GetString("PublicFeedMalformedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;cmd&quot;:&quot;news&quot;,&quot;args&quot;:{&quot;itemid&quot;:40705006,&quot;lang&quot;:&quot;da&quot;,&quot;datetime&quot;:&quot;2010-12-08 22:15:00&quot;,&quot;sourceid&quot;:6,&quot;headline&quot;:&quot;Amerikanske aktieindeks kl. 22:15&quot;,&quot;instruments&quot;:[{&quot;identifier&quot;:&quot;101&quot;,&quot;marketID&quot;:&quot;11&quot;}]}}.
        /// </summary>
        internal static string PublicFeedNewsMessage {
            get {
                return ResourceManager.GetString("PublicFeedNewsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;cmd&quot;:&quot;price&quot;,&quot;args&quot;:{&quot;i&quot;:&quot;1843&quot;,&quot;m&quot;:30,&quot;t&quot;:&quot;price&quot;,&quot;trade_timestamp&quot;:&quot;2010-01-22 16:17:23&quot;,&quot;tick_timestamp&quot;:&quot;2010-01-22 16:18:42&quot;,&quot;bid&quot;:&quot;0.00&quot;,&quot;bid_volume&quot;:0,&quot;ask&quot;:101.00,&quot;ask_volume&quot;:200,&quot;close&quot;:101.00,&quot;high&quot;:101.00,&quot;last&quot;:101.00,&quot;last_volume&quot;:200,&quot;lot_size&quot;:&quot;1&quot;,&quot;low&quot;:101.00,&quot;open&quot;:0.00,&quot;turnover&quot;:6605400,&quot;turnover_volume&quot;:65400}}.
        /// </summary>
        internal static string PublicFeedPriceMessage {
            get {
                return ResourceManager.GetString("PublicFeedPriceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;cmd&quot;:&quot;trade&quot;,&quot;args&quot;:{&quot;i&quot;:&quot;1843&quot;,&quot;m&quot;:30,&quot;t&quot;:&quot;trade&quot;,&quot;trade_timestamp&quot;:&quot;2010-01-22 16:24:04&quot;,&quot;price&quot;:101.00,&quot;volume&quot;:200,&quot;baseprice&quot;:101.00,&quot;broker_buying&quot;:&quot;ZCFT&quot;,&quot;broker_selling&quot;:&quot;ZCFT&quot;}}.
        /// </summary>
        internal static string PublicFeedTradeMessage {
            get {
                return ResourceManager.GetString("PublicFeedTradeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;cmd&quot;:&quot;trading_status&quot;,&quot;args&quot;:{&quot;i&quot;:&quot;4208&quot;,&quot;m&quot;:11,&quot;t&quot;:&quot;trading_status&quot;,&quot;timestamp&quot;:&quot;2010-01-25 09:00:00&quot;,&quot;status&quot;:&quot;C&quot;,&quot;source_status&quot;:&quot;ContinuousTrading&quot;}}.
        /// </summary>
        internal static string PublicFeedTradingStatusMessage {
            get {
                return ResourceManager.GetString("PublicFeedTradingStatusMessage", resourceCulture);
            }
        }
    }
}
